In [1]:
# =========================================================
# 0) Import demo dataset with artificial missing values
# =========================================================
import pandas as pd

# File path (adjust if needed)
csv_path = "C:/Users/customer/Desktop/MyVideos/UDEMY LESSONS/IFRS 9 Python/DQ/with_missing_ifrs9_pit_pd.csv"

# Load CSV (similar to PROC IMPORT)
df = pd.read_csv(csv_path)

print("✅ Dataset Loaded")
print("Shape:", df.shape)
print(df.head())

print("\n=== Data Types (PROC CONTENTS equivalent) ===")
print(df.dtypes)

✅ Dataset Loaded
Shape: (5000, 15)
   account_id report_date   age employment_status marital_status  dependents  \
0     9449975    1/1/2019  36.0          Employed         Single           3
1     6228566   11/1/2019  66.0          Employed        Married           0
2     3844180    7/1/2021  57.0          Employed            NaN           0
3     6931161    9/1/2018  21.0          Employed        Married           3
4     2655016    9/1/2018  38.0          Employed        Married           2

  region  internal_score  dpd  credit_utilization  macro_gdp_growth  \
0   West           551.0   99                0.42              4.33
1   West           868.0  139                1.49              0.29
2  South           351.0   27                0.43              2.29
3  South           755.0  154                 NaN              2.50
4   West           802.0  119                0.73              3.31

   macro_unemployment  macro_interest_rate  stage  default_flag
0                4.51                 3.36      3             1
1                6.18                 2.36      3             1
2                4.14                 3.41      2             0
3                6.88                 3.23      3             1
4                4.32                 2.90      3             1

=== Data Types (PROC CONTENTS equivalent) ===
account_id               int64
report_date             object
age                    float64
employment_status       object
marital_status          object
dependents               int64
region                  object
internal_score         float64
dpd                      int64
credit_utilization     float64
macro_gdp_growth       float64
macro_unemployment     float64
macro_interest_rate    float64
stage                    int64
default_flag             int64
dtype: object

In [2]:
df.head(30)

,account_id,report_date,age,employment_status,marital_status,dependents,region,internal_score,dpd,credit_utilization,macro_gdp_growth,macro_unemployment,macro_interest_rate,stage,default_flag
0,9449975,1/1/2019,36.0,Employed,Single,3,West,551.0,99,0.42,4.33,4.51,3.36,3,1
1,6228566,11/1/2019,66.0,Employed,Married,0,West,868.0,139,1.49,0.29,6.18,2.36,3,1
2,3844180,7/1/2021,57.0,Employed,NaN,0,South,351.0,27,0.43,2.29,4.14,3.41,2,0
3,6931161,9/1/2018,21.0,Employed,Married,3,South,755.0,154,NaN,2.50,6.88,3.23,3,1
4,2655016,9/1/2018,38.0,Employed,Married,2,West,802.0,119,0.73,3.31,4.32,2.90,3,1
5,8887739,7/1/2021,28.0,NaN,Divorced,2,North,498.0,5,0.82,2.53,6.05,3.70,2,0
6,7189573,12/1/2021,37.0,Employed,Married,3,East,561.0,147,0.91,1.76,4.58,2.92,3,1
7,2034586,12/1/2022,58.0,NaN,Married,0,South,860.0,90,1.28,2.75,3.61,2.86,3,1
8,6445315,1/1/2018,NaN,Employed,Married,1,North,761.0,0,0.62,2.52,6.66,3.37,2,0
9,7529845,8/1/2018,45.0,NaN,Single,4,South,822.0,98,0.36,2.01,2.34,3.18,3,1
10,9659522,10/1/2021,22.0,Self-Employed,Married,4,West,566.0,2,0.44,1.60,4.04,2.92,2,0
11,9767088,6/1/2020,52.0,Self-Employed,Married,4,South,761.0,51,1.45,1.66,1.97,2.10,2,0
12,3412149,1/1/2018,NaN,Employed,Divorced,2,North,303.0,103,1.05,1.93,5.30,2.63,3,1
13,3155748,5/1/2020,41.0,Self-Employed,Married,2,South,884.0,129,1.44,1.20,6.01,3.30,3,1
14,7662314,10/1/2018,41.0,NaN,Married,0,East,NaN,93,1.02,2.55,6.13,2.71,3,1
15,8084364,4/1/2022,59.0,Employed,Divorced,4,South,602.0,0,0.14,2.12,3.96,3.61,2,0
16,1428988,7/1/2022,54.0,Unemployed,Single,3,West,871.0,1,NaN,3.00,4.84,2.34,2,0
17,2897951,7/1/2020,39.0,Self-Employed,Single,4,North,662.0,17,1.46,4.10,5.41,2.82,2,0
18,5168962,8/1/2021,51.0,Employed,Single,1,East,487.0,137,1.01,1.01,4.17,2.52,3,1
19,9047252,4/1/2018,57.0,Self-Employed,Married,1,West,842.0,0,NaN,5.81,2.17,3.25,2,0
20,3694287,9/1/2021,44.0,Retired,Married,4,West,545.0,21,0.52,2.65,4.83,3.45,2,0
21,5300915,10/1/2020,42.0,Retired,Married,3,South,674.0,2,NaN,0.74,3.18,3.52,2,0
22,9948331,1/1/2021,60.0,Retired,Single,2,North,592.0,90,1.17,1.24,4.06,3.80,3,1
23,3526954,1/1/2021,NaN,Unemployed,Married,0,North,876.0,23,1.36,1.99,5.52,3.17,2,0
24,2404962,10/1/2020,66.0,Employed,Married,2,West,716.0,55,1.14,0.82,5.78,3.72,2,0
25,8002587,6/1/2021,43.0,Self-Employed,Married,3,West,NaN,130,0.79,3.13,6.31,2.28,3,1
26,3089319,1/1/2019,NaN,Employed,Married,0,West,NaN,144,0.34,1.77,6.84,2.68,3,1
27,2752683,5/1/2018,58.0,Self-Employed,Married,1,North,829.0,0,1.16,3.29,5.31,2.77,2,0
28,3795126,2/1/2019,42.0,Employed,Single,1,South,745.0,0,1.03,0.86,4.99,3.29,2,0
29,9315390,2/1/2020,NaN,NaN,Divorced,0,East,321.0,90,0.74,2.38,4.37,3.01,3,1

In [3]:

# =========================================================
# 1) Missing Level for Categorical (treat missing as 'Missing')
# =========================================================

# Identify categorical columns automatically
cat_cols = [c for c in df.columns if df[c].dtype == "object"]

print("\nCategorical columns detected:", cat_cols)

# Replace missing with 'Missing' (SAS: coalescec())
df_miss = df.copy()
for c in cat_cols:
    df_miss[c] = df_miss[c].fillna("Missing").astype(str).replace({"": "Missing"})


# =========================================================
# 2) Frequency tables (PROC FREQ equivalent)
# =========================================================
print("\n=== Frequency Tables (PROC FREQ equivalent) ===")
for c in cat_cols:
    print(f"\n--- {c} ---")
    print(df_miss[c].value_counts(dropna=False))


# =========================================================
# 3) Print first 200 rows (PROC PRINT OBS=200)
# =========================================================
print("\n=== First 200 Rows (PROC PRINT OBS=200) ===")
print(df_miss.head(10))


# Save cleaned version for next steps
output_path = "/mnt/data/demo_missing_level_python.csv"
df_miss.to_csv(output_path, index=False)

print("\n✅ Cleaned dataset saved to:", output_path)

Categorical columns detected: ['report_date', 'employment_status', 'marital_status', 'region']

=== Frequency Tables (PROC FREQ equivalent) ===

--- report_date ---
report_date
6/1/2019     102
6/1/2021     100
2/1/2020      99
3/1/2021      99
3/1/2019      96
1/1/2019      95
10/1/2022     95
2/1/2018      94
12/1/2019     94
6/1/2022      93
12/1/2018     93
1/1/2022      93
5/1/2019      91
9/1/2022      91
10/1/2018     91
4/1/2019      89
9/1/2018      89
9/1/2020      88
11/1/2019     88
1/1/2021      87
5/1/2020      86
10/1/2020     86
12/1/2021     86
7/1/2018      85
4/1/2020      85
1/1/2018      84
2/1/2019      83
2/1/2021      83
2/1/2022      83
11/1/2022     83
1/1/2020      82
8/1/2021      82
8/1/2019      82
9/1/2019      82
11/1/2018     82
6/1/2018      81
6/1/2020      81
12/1/2020     81
7/1/2020      81
10/1/2019     79
7/1/2022      79
4/1/2022      78
5/1/2018      78
4/1/2018      77
7/1/2019      77
3/1/2018      77
5/1/2021      76
8/1/2022      76
3/1/2022      75
7/1/2021      75
10/1/2021     75
3/1/2020      73
8/1/2020      73
8/1/2018      72
11/1/2020     72
11/1/2021     70
9/1/2021      70
4/1/2021      69
5/1/2022      68
12/1/2022     66
Name: count, dtype: int64

--- employment_status ---
employment_status
Employed         2552
Unemployed        848
Self-Employed     659
Missing           500
Retired           441
Name: count, dtype: int64

--- marital_status ---
marital_status
Married     2021
Single      1794
Missing      500
Divorced     467
Widowed      218
Name: count, dtype: int64

--- region ---
region
West     1290
North    1269
East     1239
South    1202
Name: count, dtype: int64

=== First 200 Rows (PROC PRINT OBS=200) ===
   account_id report_date   age employment_status marital_status  dependents  \
0     9449975    1/1/2019  36.0          Employed         Single           3
1     6228566   11/1/2019  66.0          Employed        Married           0
2     3844180    7/1/2021  57.0          Employed        Missing           0
3     6931161    9/1/2018  21.0          Employed        Married           3
4     2655016    9/1/2018  38.0          Employed        Married           2
5     8887739    7/1/2021  28.0           Missing       Divorced           2
6     7189573   12/1/2021  37.0          Employed        Married           3
7     2034586   12/1/2022  58.0           Missing        Married           0
8     6445315    1/1/2018   NaN          Employed        Married           1
9     7529845    8/1/2018  45.0           Missing         Single           4

  region  internal_score  dpd  credit_utilization  macro_gdp_growth  \
0   West           551.0   99                0.42              4.33
1   West           868.0  139                1.49              0.29
2  South           351.0   27                0.43              2.29
3  South           755.0  154                 NaN              2.50
4   West           802.0  119                0.73              3.31
5  North           498.0    5                0.82              2.53
6   East           561.0  147                0.91              1.76
7  South           860.0   90                1.28              2.75
8  North           761.0    0                0.62              2.52
9  South           822.0   98                0.36              2.01

   macro_unemployment  macro_interest_rate  stage  default_flag
0                4.51                 3.36      3             1
1                6.18                 2.36      3             1
2                4.14                 3.41      2             0
3                6.88                 3.23      3             1
4                4.32                 2.90      3             1
5                6.05                 3.70      2             0
6                4.58                 2.92      3             1
7                3.61                 2.86      3             1
8                6.66                 3.37      2             0
9                2.34                 3.18      3             1

✅ Cleaned dataset saved to: /mnt/data/demo_missing_level_python.csv

In [4]:
df_miss.head(30)

,account_id,report_date,age,employment_status,marital_status,dependents,region,internal_score,dpd,credit_utilization,macro_gdp_growth,macro_unemployment,macro_interest_rate,stage,default_flag
0,9449975,1/1/2019,36.0,Employed,Single,3,West,551.0,99,0.42,4.33,4.51,3.36,3,1
1,6228566,11/1/2019,66.0,Employed,Married,0,West,868.0,139,1.49,0.29,6.18,2.36,3,1
2,3844180,7/1/2021,57.0,Employed,Missing,0,South,351.0,27,0.43,2.29,4.14,3.41,2,0
3,6931161,9/1/2018,21.0,Employed,Married,3,South,755.0,154,NaN,2.50,6.88,3.23,3,1
4,2655016,9/1/2018,38.0,Employed,Married,2,West,802.0,119,0.73,3.31,4.32,2.90,3,1
5,8887739,7/1/2021,28.0,Missing,Divorced,2,North,498.0,5,0.82,2.53,6.05,3.70,2,0
6,7189573,12/1/2021,37.0,Employed,Married,3,East,561.0,147,0.91,1.76,4.58,2.92,3,1
7,2034586,12/1/2022,58.0,Missing,Married,0,South,860.0,90,1.28,2.75,3.61,2.86,3,1
8,6445315,1/1/2018,NaN,Employed,Married,1,North,761.0,0,0.62,2.52,6.66,3.37,2,0
9,7529845,8/1/2018,45.0,Missing,Single,4,South,822.0,98,0.36,2.01,2.34,3.18,3,1
10,9659522,10/1/2021,22.0,Self-Employed,Married,4,West,566.0,2,0.44,1.60,4.04,2.92,2,0
11,9767088,6/1/2020,52.0,Self-Employed,Married,4,South,761.0,51,1.45,1.66,1.97,2.10,2,0
12,3412149,1/1/2018,NaN,Employed,Divorced,2,North,303.0,103,1.05,1.93,5.30,2.63,3,1
13,3155748,5/1/2020,41.0,Self-Employed,Married,2,South,884.0,129,1.44,1.20,6.01,3.30,3,1
14,7662314,10/1/2018,41.0,Missing,Married,0,East,NaN,93,1.02,2.55,6.13,2.71,3,1
15,8084364,4/1/2022,59.0,Employed,Divorced,4,South,602.0,0,0.14,2.12,3.96,3.61,2,0
16,1428988,7/1/2022,54.0,Unemployed,Single,3,West,871.0,1,NaN,3.00,4.84,2.34,2,0
17,2897951,7/1/2020,39.0,Self-Employed,Single,4,North,662.0,17,1.46,4.10,5.41,2.82,2,0
18,5168962,8/1/2021,51.0,Employed,Single,1,East,487.0,137,1.01,1.01,4.17,2.52,3,1
19,9047252,4/1/2018,57.0,Self-Employed,Married,1,West,842.0,0,NaN,5.81,2.17,3.25,2,0
20,3694287,9/1/2021,44.0,Retired,Married,4,West,545.0,21,0.52,2.65,4.83,3.45,2,0
21,5300915,10/1/2020,42.0,Retired,Married,3,South,674.0,2,NaN,0.74,3.18,3.52,2,0
22,9948331,1/1/2021,60.0,Retired,Single,2,North,592.0,90,1.17,1.24,4.06,3.80,3,1
23,3526954,1/1/2021,NaN,Unemployed,Married,0,North,876.0,23,1.36,1.99,5.52,3.17,2,0
24,2404962,10/1/2020,66.0,Employed,Married,2,West,716.0,55,1.14,0.82,5.78,3.72,2,0
25,8002587,6/1/2021,43.0,Self-Employed,Married,3,West,NaN,130,0.79,3.13,6.31,2.28,3,1
26,3089319,1/1/2019,NaN,Employed,Married,0,West,NaN,144,0.34,1.77,6.84,2.68,3,1
27,2752683,5/1/2018,58.0,Self-Employed,Married,1,North,829.0,0,1.16,3.29,5.31,2.77,2,0
28,3795126,2/1/2019,42.0,Employed,Single,1,South,745.0,0,1.03,0.86,4.99,3.29,2,0
29,9315390,2/1/2020,NaN,Missing,Divorced,0,East,321.0,90,0.74,2.38,4.37,3.01,3,1